services:
  front:
    build: ./frontend
    container_name: frontend-service
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 3030:80
    volumes:
      - ./frontend:/code
    depends_on:
      - api

  api:
    build: ./api
    container_name: api-service
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 6969:80
      - 5678:5678
    volumes:
      - ./api:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
        - ./redis_data:/data